import 'package:agritech/styles/color_styles.dart';
import 'package:agritech/styles/text_styles.dart';
import 'package:flutter/material.dart';

class TermsAndCondition extends StatelessWidget {
  const TermsAndCondition({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: ColorStyle.brandRed,
        elevation: 0,
        title: Center(
          child: Text(
            "Terms of use",
            textAlign: TextAlign.center,
            style: MyTextStyles.header.copyWith(
              color: Colors.white,
            ),
          ),
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(21.0),
        child: Container(
          width: double.infinity,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(12),
            color: Color(0xffE9E9E9),
          ),
          child: Column(
            children: [
              SizedBox(height: 30),
              Text(
                "Terms of Use",
                style: MyTextStyles.header,
                textAlign: TextAlign.center,
              ),
              Padding(
                padding: const EdgeInsets.all(20.0),
                child: Text(
                  " Welcome to the AGRITECH mobile app. Please read these Terms & Conditions of Use carefully. The following Terms of Use govern your use and access of the Platform (defined below) and the use of the Services. By accessing the Platform and/or using the Services, you agree to be bound by these Terms of Use. If you do not agree to these Terms of Use, do not access and/or use this Platform or the Services. The Terms of Use provides you with information on the do’s and don’ts on the access and use of the  Platform. If you are using the engagement tools provided by Samson on AGRITECH mobile applications, the Platform Engagement Tools Terms & Conditions shall apply.  If you are purchasing Products on Samson E-Commerce App, the reference to the Terms & Conditions of Sale will depend on which channel you purchase the Product from.  If you are accessing, uploading or viewing (1) Livestream Content; (2) content generated by Samson which is uploaded or viewed on any Samson Platform; and (3) content generated by third parties hired by Samson, the Content Terms of Service shall apply.",
                  style: MyTextStyles.text,
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}
